### ISSUE TITLE
Specify line numbers and give more context on errors

### ISSUE THREAD

**Issue by EmilStenstrom** [danthedeckie/html5validate#2]
Hi! Thanks for a great little library! I've used it to write a [crawler](https://github.com/EmilStenstrom/friendlybit/blob/master/commands/crawl.py) that goes through my whole site on localhost and validates all HTML. Great when there's lots of user generated content that I want to make sure doesn't break my site.

Anyways. I'm not sure how hard this is, but I would really like better error messages. Here's an example from my script:

```
Checking: http://localhost:8000/js/lazy-loading-asyncronous-javascript/                                        --> Traceback (most recent call last):
  File "commands/crawl.py", line 88, in <module>
    main()
  File "commands/crawl.py", line 77, in main
    print(("VALID" if html5validate.validate(html) is None else "INVALID"))
  File "/Users/EmilStenstrom/.pyenv/versions/friendlybit/lib/python3.8/site-packages/html5validate.py", line 36, in validate
    dom = PARSER.parse(text)
  File "/Users/EmilStenstrom/.pyenv/versions/friendlybit/lib/python3.8/site-packages/html5lib/html5parser.py", line 289, in parse
    self._parse(stream, False, None, *args, **kwargs)
  File "/Users/EmilStenstrom/.pyenv/versions/friendlybit/lib/python3.8/site-packages/html5lib/html5parser.py", line 134, in _parse
    self.mainLoop()
  File "/Users/EmilStenstrom/.pyenv/versions/friendlybit/lib/python3.8/site-packages/html5lib/html5parser.py", line 241, in mainLoop
    new_token = phase.processStartTag(new_token)
  File "/Users/EmilStenstrom/.pyenv/versions/friendlybit/lib/python3.8/site-packages/html5lib/html5parser.py", line 472, in processStartTag
    return self.startTagHandler[token["name"]](token)
  File "/Users/EmilStenstrom/.pyenv/versions/friendlybit/lib/python3.8/site-packages/html5lib/html5parser.py", line 1154, in startTagA
    self.parser.parseError("unexpected-start-tag-implies-end-tag",
  File "/Users/EmilStenstrom/.pyenv/versions/friendlybit/lib/python3.8/site-packages/html5lib/html5parser.py", line 326, in parseError
    raise ParseError(E[errorcode] % datavars)
html5lib.html5parser.ParseError: Unexpected start tag (a) implies end tag (a).
```

The checked HTML files has hundreds of links, and just finding which one is missing a `</a>` is a lot of unnecessary work.

Another:

```
Checking: http://localhost:8000/css/ie7-hover-bug-z-index-ignored-and-other-properties/                        --> Traceback (most recent call last):
  File "commands/crawl.py", line 88, in <module>
    main()
  File "commands/crawl.py", line 77, in main
    print(("VALID" if html5validate.validate(html) is None else "INVALID"))
  File "/Users/EmilStenstrom/.pyenv/versions/friendlybit/lib/python3.8/site-packages/html5validate.py", line 36, in validate
    dom = PARSER.parse(text)
  File "/Users/EmilStenstrom/.pyenv/versions/friendlybit/lib/python3.8/site-packages/html5lib/html5parser.py", line 289, in parse
    self._parse(stream, False, None, *args, **kwargs)
  File "/Users/EmilStenstrom/.pyenv/versions/friendlybit/lib/python3.8/site-packages/html5lib/html5parser.py", line 134, in _parse
    self.mainLoop()
  File "/Users/EmilStenstrom/.pyenv/versions/friendlybit/lib/python3.8/site-packages/html5lib/html5parser.py", line 217, in mainLoop
    self.parseError(new_token["data"], new_token.get("datavars", {}))
  File "/Users/EmilStenstrom/.pyenv/versions/friendlybit/lib/python3.8/site-packages/html5lib/html5parser.py", line 326, in parseError
    raise ParseError(E[errorcode] % datavars)
html5lib.html5parser.ParseError: Unexpected character after attribute value.
```

Doesn't give any context over where in the document it is, which again takes a lot of work when the document is large.

Any chance the error messages could be made mode descriptive?

**Comment by danthedeckie** [comment]
I am so with you on needing this, mate 😄 

Alas, the html5lib parser didn't seem to have an easy way to do this (from memory, I haven't worked on this in a while).

I think last time I was hacking on the project, I realised I'd probably need to drop html5lib and write a strict html parser directly which had access to line numbers and other context.

In terms of context, it would be super useful (I think) if it said something like

```
    Line 24: html>body>div#header>div>div
    Unexpected <A> start tag implies </A> end tag.
```

Or some similar way to show where structurally in the document the problem is?

What do you think?

**Comment by EmilStenstrom** [comment]
I looked around a bit on other ways of doing this, and the "proper" way is to use validator.nu, which is available as open source, and can be run locally. I say proper, because it's extremely thorough, and is built by the same people that wrote HTML5, just to be a validator. Problem is, it's written in Java, which requires a new environment setup... I just wanted something in Python.

I googled a bit, and getting a hold of the line number is tricky. I see that pymedusa has found an attribute called TRACK_LINE_NUMBERS, which looks promising? https://github.com/pymedusa/Medusa/blob/master/ext2/bs4/builder/_html5lib.py#L50

If that doesn't pan out, maybe switching to html5parser would work? It seems to support line_number_attr, which says what attribute in a node you wish to store the line number on: https://html5-parser.readthedocs.io/en/latest/

About how the error message should look, I think I like how validator.nu does it: https://validator.nu/?doc=http%3A%2F%2Fyahoo.com

They simply show part of the source code, from ~10 character before where the error occured, to 10 characters after where that tag ends. 

Showing where in the three the error is doesn't help as much, as you don't know which div to traverse, if there are many... Adding something like `html>body>div#header>div[5]>div[3]` would be better, but you still would have to traverse the document manually, as there are no easy way to find that location in the HTML source.

**Comment by danthedeckie** [comment]
Yeah.  There are HTML parsers that do use external services, or java, or whatever.  But this project isn't going to :-)  That's why I started this one!

Theres a new branch I'm slowly writing a tag parser in - which contains the line and character numbers, which should work.   If the idea is to be strict and fussy, then the spec isn't *too* complicated really... It doesn't have to cope with too many edgecases, it can just crash with an error.

It might be worth (maybe) splitting out the tree-structure / attributes validation at some point - then you could use that to validate XML / HTML / hybrid stuff too? I dunno.

I like your idea about displaying position in the tree as well as just line numbers, that's a really good idea.

Those are great links, thanks for finding them.
It would be really cool to use some of those external test suites at some point.

I'll see how far along I come with the actual parsing branch, maybe I'm missing something, but I feel like it's not going to be that much of a monster.
